### ISSUE TITLE
Affine transformation explanation

### ISSUE THREAD

**Issue by TheBluePhoenix10** [Kasidit0052/Matching-Openpose#1]
Hello. 
Can you explain how you have used affine transformation and how have you calculated affine matrix?
I am trying to modify it for a 7 keypoint pose matching algo but I am getting errors, like None values in the output of the transform.

eg. [(None, None), (None, None), (56, 72), (None, None), (348, 49), (369, 197), (383, 338)]

I could not understand how exactly have you implemented the transformation as your implementation is very different from that done online.

can you explain me how you have calculated q,p,A and T and how to modify the following code for 7 keypoints?

    q = np.array([[pose1[1][0]],[pose1[1][1]],[pose1[8][0]],[pose1[8][1]]], np.float)

    p = np.array([[pose2[1][0], pose2[1][1], 1.0, 0.0, 0.0, 0.0], \
                  [0.0, 0.0, 0.0, pose2[1][0], pose2[1][1], 1.0], \
                  [pose2[8][0], pose2[8][1], 1.0, 0.0, 0.0, 0.0], \
                  [0.0, 0.0, 0.0, pose2[8][0], pose2[8][1], 1.0]], np.float)

    A, res, rank, s = np.linalg.lstsq(p, q)

    T = np.array([[A[0], A[1], A[2]],[A[3], A[4], A[5]],[0.0, 0.0, 1.0]], np.float)

    return T

**Comment by Kasidit0052** [comment]
**Hello,**

Thank you for interested in MatchingOpenpose. For the affine transformation concept, we normally use least square approximation method to approximate best transformation matrix that correctly map one pose to another. 

In this **COLAB**, we use neck coordinate(1) and hip coordinate(8) as a parameter in `p` and `q`. You should modify those parameters in case of custom keypoints. None value in the output of the transform usually happens when there is null coordinate position or when `np.linalg.lstsq(p, q)` fail to find the best solution. I would suggest creating a try except condition that provide a backup method when affine transformation fails.

### This is the Affine Transformation Visualization which might help you to understand
-----------------------------------------------------------------------------------------------------------------------
![AffineTransform1](https://user-images.githubusercontent.com/60087310/135118498-d0c20a9c-3f92-47b5-b250-fef89615db18.png)

**Comment by TheBluePhoenix10** [comment]
Thank you for the detailed answer. I could figure out that you implemented affine transform by basically overlapping the line connecting points 1 and 8 of both the reference and destination pose, and then applying the same transformation on the remaining points. Currently, the problem is that my affine transform fails all the time, and that is the only part where I have been failing. I have been successful in porting other things you have done on jupyter into a .py file structure. I am trying to basically use blazepose instead of posenet and use pure python instead of collab or jupyter. Can we use the cv2 function to calculate affine matrix? I am having problems using that too but I think it will be more efficient once I figure out correctly how to use it.

**Comment by Kasidit0052** [comment]
Yes, It's possible to use the `cv2.getAffineTransform` as an alternative solution to find the affine matrix. However, you should also make sure that pose coordinates is not `none` when pass through cv affine transform.

**Comment by TheBluePhoenix10** [comment]
I tried using the cv2.getAffineTransform but it gave me some other errors. the pose coordinates become none after i calculate the affine matrix using your method.

**Comment by Kasidit0052** [comment]
Interesting, `cv2.getAffineTransform` requires a minimum of 3 input for full 2D affine transform. What we want in this case is 
partial 2D affine transform so the code should be something like this

# Function to get Affine Transformation matrix
```
def AffineTransformCV(pose1,pose2):
    q = np.float32([[pose1[1][0], pose1[1][1]], 
                    [pose1[8][0], pose1[8][1]]])
      
    p = np.float32([[pose2[1][0], pose2[1][1]], 
                    [pose2[8][0], pose2[8][1]]])

    M, _ = cv2.estimateAffinePartial2D(p,q)
    M = np.append(M,[0,0,1]).reshape(3,3)
    return M
```

**Comment by UnstoppableJ** [comment]
> 



> Thank you for the detailed answer. I could figure out that you implemented affine transform by basically overlapping the line connecting points 1 and 8 of both the reference and destination pose, and then applying the same transformation on the remaining points. Currently, the problem is that my affine transform fails all the time, and that is the only part where I have been failing. I have been successful in porting other things you have done on jupyter into a .py file structure. I am trying to basically use blazepose instead of posenet and use pure python instead of collab or jupyter. Can we use the cv2 function to calculate affine matrix? I am having problems using that too but I think it will be more efficient once I figure out correctly how to use it.

Hello, I am sorry to interrupt you.
I am also trying to transform this jupyter project to a .py file structure. However,I have met many problems. I would be appreciated  if it is convenient for you to share your project in you github. Thank you so much!
